import { StyleSheet } from 'react-native';
import { theme } from '../../theme';

export const scannerStyles = StyleSheet.create({
  header: {
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderBottomColor: theme.colors.border,
    borderBottomWidth: 1,
    flexDirection: 'row',
    paddingBottom: 14,
    paddingHorizontal: 18,
    paddingTop: 48,
  },
  headerButton: {
    alignItems: 'center',
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  backButton: {
    backgroundColor: theme.colors.primarySoft,
    borderRadius: 14,
  },
  headerCopy: { alignItems: 'center', flex: 1 },
  title: { color: theme.colors.text, fontSize: 19, fontWeight: '900' },
  subtitle: { color: theme.colors.textMuted, fontSize: 12, marginTop: 2 },
  cameraArea: {
    backgroundColor: '#17111B',
    flex: 1,
    minHeight: 350,
    overflow: 'hidden',
  },
  camera: { ...StyleSheet.absoluteFillObject },
  overlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(23,17,27,.18)',
    flex: 1,
    justifyContent: 'center',
    padding: 24,
  },
  permissionPanel: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    padding: 32,
  },
  permissionTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '900',
    marginTop: 14,
    textAlign: 'center',
  },
  permissionText: {
    color: 'rgba(255,255,255,.68)',
    fontSize: 13,
    lineHeight: 19,
    marginTop: 7,
    textAlign: 'center',
  },
  scanFrame: {
    alignItems: 'center',
    backgroundColor: 'rgba(38,13,53,.08)',
    borderColor: 'rgba(255,255,255,.28)',
    borderRadius: 24,
    borderWidth: 1,
    height: 250,
    justifyContent: 'center',
    width: 250,
  },
  corner: {
    borderColor: theme.colors.accent,
    height: 42,
    position: 'absolute',
    width: 42,
  },
  topLeft: {
    borderLeftWidth: 5,
    borderTopLeftRadius: 22,
    borderTopWidth: 5,
    left: -2,
    top: -2,
  },
  topRight: {
    borderRightWidth: 5,
    borderTopRightRadius: 22,
    borderTopWidth: 5,
    right: -2,
    top: -2,
  },
  bottomLeft: {
    borderBottomLeftRadius: 22,
    borderBottomWidth: 5,
    borderLeftWidth: 5,
    bottom: -2,
    left: -2,
  },
  bottomRight: {
    borderBottomRightRadius: 22,
    borderBottomWidth: 5,
    borderRightWidth: 5,
    bottom: -2,
    right: -2,
  },
  scanLine: {
    backgroundColor: theme.colors.accent,
    height: 2,
    left: 20,
    position: 'absolute',
    right: 20,
    top: 124,
  },
  cameraHint: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
    marginTop: 22,
    textAlign: 'center',
  },
  cameraSubtext: {
    color: 'rgba(255,255,255,.72)',
    fontSize: 12,
    marginTop: 5,
    textAlign: 'center',
  },
  flashButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,.16)',
    borderRadius: 24,
    height: 48,
    justifyContent: 'center',
    marginTop: 18,
    width: 48,
  },
  actions: {
    backgroundColor: theme.colors.surface,
    paddingBottom: 106,
    paddingHorizontal: 20,
    paddingTop: 14,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: theme.colors.accent,
    borderRadius: 17,
    flexDirection: 'row',
    height: 56,
    justifyContent: 'center',
  },
  primaryText: {
    color: theme.colors.primaryDark,
    fontSize: 15,
    fontWeight: '900',
    marginLeft: 8,
  },
  secondaryButton: {
    alignItems: 'center',
    borderColor: theme.colors.primary,
    borderRadius: 17,
    borderWidth: 1,
    flexDirection: 'row',
    height: 52,
    justifyContent: 'center',
    marginTop: 10,
  },
  secondaryText: {
    color: theme.colors.primary,
    fontSize: 14,
    fontWeight: '800',
    marginLeft: 8,
  },
});
