import { StyleSheet } from 'react-native';
import { theme } from '../theme';

export const companyPermissionStyles = StyleSheet.create({
  companyCard: {
    backgroundColor: theme.colors.primaryDark,
    borderRadius: 20,
    marginTop: 20,
    padding: 18,
  },
  companyTop: { alignItems: 'center', flexDirection: 'row' },
  companyIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,.14)',
    borderRadius: 15,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  companyInfo: { flex: 1, marginLeft: 12 },
  companyName: { color: '#FFFFFF', fontSize: 17, fontWeight: '900' },
  companyMeta: { color: 'rgba(255,255,255,.7)', fontSize: 12, marginTop: 3 },
  scope: {
    alignItems: 'center',
    borderTopColor: 'rgba(255,255,255,.14)',
    borderTopWidth: 1,
    flexDirection: 'row',
    marginTop: 14,
    paddingTop: 14,
  },
  scopeText: { color: 'rgba(255,255,255,.78)', flex: 1, fontSize: 12, marginLeft: 8 },
  sectionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 5,
    marginTop: 24,
  },
  sectionTitle: { color: theme.colors.text, fontSize: 19, fontWeight: '900' },
  countText: { color: theme.colors.textMuted, fontSize: 12, fontWeight: '800' },
  memberCard: {
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.border,
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 10,
    padding: 14,
  },
  row: { alignItems: 'center', flexDirection: 'row' },
  avatar: {
    alignItems: 'center',
    borderRadius: 14,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  memberInfo: { flex: 1, marginLeft: 11 },
  memberName: { color: theme.colors.text, fontSize: 14, fontWeight: '900' },
  memberEmail: { color: theme.colors.textMuted, fontSize: 11, marginTop: 2 },
  memberCompany: { color: theme.colors.primary, fontSize: 10, fontWeight: '700', marginTop: 2 },
  rolePill: { borderRadius: theme.radius.pill, paddingHorizontal: 9, paddingVertical: 6 },
  roleText: { fontSize: 10, fontWeight: '900' },
  accessText: { color: theme.colors.textMuted, fontSize: 11, lineHeight: 16, marginTop: 10 },
  addButton: {
    alignItems: 'center',
    backgroundColor: theme.colors.accent,
    borderRadius: 16,
    flexDirection: 'row',
    height: 54,
    justifyContent: 'center',
    marginTop: 14,
  },
  addButtonText: { color: theme.colors.primaryDark, fontSize: 14, fontWeight: '900', marginLeft: 7 },
  secondaryAddButton: {
    alignItems: 'center',
    backgroundColor: theme.colors.primarySoft,
    borderColor: theme.colors.primary,
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    height: 52,
    justifyContent: 'center',
    marginTop: 12,
  },
  secondaryAddButtonText: { color: theme.colors.primary, fontSize: 14, fontWeight: '900', marginLeft: 7 },
  formCard: {
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.border,
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 12,
    padding: 16,
  },
  formTitle: { color: theme.colors.text, fontSize: 16, fontWeight: '900' },
  formSectionLabel: { color: theme.colors.text, fontSize: 15, fontWeight: '900', marginTop: 18 },
  formActions: { flexDirection: 'row', gap: 9, marginTop: 16 },
  secondaryButton: {
    alignItems: 'center',
    borderColor: theme.colors.border,
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    height: 48,
    justifyContent: 'center',
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: theme.colors.primary,
    borderRadius: 14,
    flex: 1,
    height: 48,
    justifyContent: 'center',
  },
  secondaryText: { color: theme.colors.textMuted, fontSize: 13, fontWeight: '800' },
  primaryText: { color: '#FFFFFF', fontSize: 13, fontWeight: '900' },
  permissionCard: {
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.border,
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 10,
    padding: 15,
  },
  permissionTitle: { color: theme.colors.text, fontSize: 13, fontWeight: '900' },
  permissionText: { color: theme.colors.textMuted, fontSize: 11, lineHeight: 17, marginTop: 4 },
  infoBox: {
    alignItems: 'flex-start',
    backgroundColor: theme.colors.primarySoft,
    borderRadius: 15,
    flexDirection: 'row',
    marginBottom: 6,
    marginTop: 22,
    padding: 13,
  },
  infoText: { color: theme.colors.textMuted, flex: 1, fontSize: 11, lineHeight: 17, marginLeft: 9 },
});
