import { StyleSheet } from 'react-native';
import { theme } from '../theme';

export const costStyles = StyleSheet.create({
  header: { backgroundColor: theme.colors.primaryDark, paddingBottom: 24, paddingHorizontal: 20, paddingTop: 52 },
  headerRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  title: { color: '#FFFFFF', fontSize: 28, fontWeight: '900' },
  subtitle: { color: 'rgba(255,255,255,.7)', fontSize: 12, marginTop: 4 },
  headerIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,.12)',
    borderRadius: 14,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  totalCard: {
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.border,
    borderRadius: 22,
    borderWidth: 1,
    marginTop: 18,
    padding: 18,
  },
  label: { color: theme.colors.textMuted, fontSize: 12, fontWeight: '700' },
  total: { color: theme.colors.text, fontSize: 30, fontWeight: '900', marginTop: 4 },
  progressTrack: {
    backgroundColor: theme.colors.primarySoft,
    borderRadius: 5,
    height: 8,
    marginTop: 14,
    overflow: 'hidden',
  },
  progressFill: { height: '100%' },
  totalFooter: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 8 },
  smallText: { color: theme.colors.textMuted, fontSize: 12 },
  summaryRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 12 },
  summaryCard: {
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.border,
    borderRadius: 18,
    borderWidth: 1,
    padding: 15,
    width: '48.5%',
  },
  iconTile: {
    alignItems: 'center',
    borderRadius: 12,
    height: 38,
    justifyContent: 'center',
    marginBottom: 12,
    width: 38,
  },
  summaryValue: { color: theme.colors.text, fontSize: 17, fontWeight: '900', marginTop: 4 },
  warning: {
    alignItems: 'center',
    backgroundColor: theme.colors.dangerSoft,
    borderColor: '#F2C8C4',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    marginTop: 12,
    padding: 14,
  },
  warningInfo: { flex: 1, marginLeft: 11 },
  warningTitle: { color: theme.colors.danger, fontSize: 14, fontWeight: '900' },
  warningText: { color: theme.colors.textMuted, fontSize: 12, lineHeight: 17, marginTop: 2 },
  sectionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 2,
    marginTop: 24,
  },
  sectionTitle: { color: theme.colors.text, fontSize: 19, fontWeight: '900' },
  linkText: { color: theme.colors.primary, fontSize: 13, fontWeight: '800' },
  expenseCard: {
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.border,
    borderRadius: 17,
    borderWidth: 1,
    flexDirection: 'row',
    marginTop: 10,
    minHeight: 68,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  expenseInfo: { flex: 1, marginLeft: 12 },
  expenseName: { color: theme.colors.text, fontSize: 14, fontWeight: '800' },
  expenseDate: { color: theme.colors.textMuted, fontSize: 11, marginTop: 3 },
  expenseValue: { color: theme.colors.text, fontSize: 13, fontWeight: '900', marginLeft: 8 },
  addButton: {
    alignItems: 'center',
    backgroundColor: theme.colors.accent,
    borderRadius: 17,
    flexDirection: 'row',
    height: 56,
    justifyContent: 'center',
    marginTop: 18,
  },
  addButtonText: { color: theme.colors.primaryDark, fontSize: 15, fontWeight: '900', marginLeft: 8 },
});
