import { StyleSheet } from 'react-native';
import { theme } from '../theme';

export const addExpenseStyles = StyleSheet.create({
  introText: {
    color: theme.colors.textMuted,
    fontSize: 14,
    lineHeight: 21,
    marginBottom: 2,
    marginTop: 20,
  },
  projectCard: {
    alignItems: 'center',
    backgroundColor: theme.colors.primarySoft,
    borderRadius: 16,
    flexDirection: 'row',
    marginTop: 14,
    padding: 14,
  },
  projectIcon: {
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderRadius: 12,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  projectInfo: { flex: 1, marginLeft: 11 },
  projectLabel: { color: theme.colors.textMuted, fontSize: 11, fontWeight: '800' },
  projectName: { color: theme.colors.text, fontSize: 14, fontWeight: '900', marginTop: 2 },
  sectionLabel: {
    color: theme.colors.textMuted,
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 7,
    marginTop: 16,
  },
  row: { flexDirection: 'row', gap: 10 },
  halfField: { flex: 1 },
  offlineNotice: {
    alignItems: 'center',
    backgroundColor: '#FFF4D6',
    borderRadius: 12,
    flexDirection: 'row',
    marginTop: 16,
    padding: 12,
  },
  offlineText: { color: '#71540D', flex: 1, fontSize: 12, marginLeft: 8 },
  submitButton: {
    alignItems: 'center',
    backgroundColor: theme.colors.accent,
    borderRadius: 16,
    flexDirection: 'row',
    height: 56,
    justifyContent: 'center',
    marginVertical: 24,
  },
  disabledButton: { opacity: 0.55 },
  submitText: {
    color: theme.colors.primaryDark,
    fontSize: 16,
    fontWeight: '900',
    marginLeft: 8,
  },
});
