import { StyleSheet } from 'react-native';
import { theme } from '../theme';

export const budgetStyles = StyleSheet.create({
  header: { backgroundColor: theme.colors.primaryDark, paddingBottom: 24, paddingHorizontal: 20, paddingTop: 48 },
  headerTop: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  title: { color: '#FFFFFF', fontSize: 28, fontWeight: '900' },
  subtitle: { color: 'rgba(255,255,255,.74)', fontSize: 13, marginTop: 5 },
  versionBadge: { backgroundColor: 'rgba(255,255,255,.13)', borderRadius: 20, paddingHorizontal: 10, paddingVertical: 7 },
  versionText: { color: '#FFFFFF', fontSize: 11, fontWeight: '800' },
  summaryCard: {
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.border,
    borderRadius: 22,
    borderWidth: 1,
    marginTop: 18,
    padding: 18,
  },
  summaryLabel: { color: theme.colors.textMuted, fontSize: 11, fontWeight: '800', letterSpacing: 0.4 },
  budgetValue: { color: theme.colors.text, fontSize: 30, fontWeight: '900', marginTop: 5 },
  progressTrack: {
    backgroundColor: theme.colors.primarySoft,
    borderRadius: 5,
    height: 8,
    marginTop: 15,
    overflow: 'hidden',
  },
  progressFill: { height: '100%' },
  progressInfo: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginTop: 8 },
  smallText: { color: theme.colors.textMuted, fontSize: 11 },
  cards: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 12 },
  miniCard: {
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.border,
    borderRadius: 18,
    borderWidth: 1,
    padding: 14,
    width: '48.5%',
  },
  iconBox: {
    alignItems: 'center',
    borderRadius: 12,
    height: 36,
    justifyContent: 'center',
    marginBottom: 10,
    width: 36,
  },
  miniLabel: { color: theme.colors.textMuted, fontSize: 11, fontWeight: '700' },
  miniValue: { color: theme.colors.text, fontSize: 16, fontWeight: '900', marginTop: 4 },
  actions: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 16 },
  actionButton: {
    alignItems: 'center',
    borderRadius: 15,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    minHeight: 50,
    padding: 10,
    width: '48.5%',
  },
  secondaryAction: { backgroundColor: theme.colors.surface, borderColor: theme.colors.border },
  primaryAction: { backgroundColor: theme.colors.accent, borderColor: theme.colors.accent },
  actionText: { fontSize: 13, fontWeight: '900', marginLeft: 7 },
  secondaryActionText: { color: theme.colors.primary },
  primaryActionText: { color: theme.colors.primaryDark },
  sectionHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8, marginTop: 26 },
  sectionTitle: { color: theme.colors.text, fontSize: 20, fontWeight: '900' },
  sectionMeta: { color: theme.colors.textMuted, fontSize: 12, fontWeight: '700' },
  serviceCard: {
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.border,
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 10,
    padding: 15,
  },
  serviceTop: { alignItems: 'flex-start', flexDirection: 'row' },
  serviceIcon: { alignItems: 'center', borderRadius: 13, height: 42, justifyContent: 'center', width: 42 },
  serviceInfo: { flex: 1, marginLeft: 11 },
  serviceName: { color: theme.colors.text, fontSize: 14, fontWeight: '900' },
  serviceCode: { color: theme.colors.textMuted, fontSize: 11, marginTop: 3 },
  serviceValue: { color: theme.colors.text, fontSize: 14, fontWeight: '900', marginLeft: 8 },
  detailRow: {
    borderTopColor: theme.colors.border,
    borderTopWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 13,
    paddingTop: 12,
  },
  detail: { flex: 1 },
  detailLabel: { color: theme.colors.textMuted, fontSize: 10, fontWeight: '700' },
  detailValue: { color: theme.colors.text, fontSize: 12, fontWeight: '900', marginTop: 3 },
  note: {
    alignItems: 'flex-start',
    backgroundColor: theme.colors.primarySoft,
    borderRadius: 16,
    flexDirection: 'row',
    marginBottom: 8,
    marginTop: 18,
    padding: 14,
  },
  noteText: { color: theme.colors.textMuted, flex: 1, fontSize: 12, lineHeight: 17, marginLeft: 9 },
});
